name: Sullaimplugin
version: '1.4'
main: io.github.rimurutempestj.sullaimplugin.Sullaimplugin
api-version: 1.17
authors: [ sullaim ]
description: Sullaim's test plugin
website: https://github.com/rimurutempestj/sullaimplugin

commands:
  testslime:
    description: testcommandslime
    usage: /testslime
  kickslime:
    description: kickslime
    usage: /kickslime
  gm:
    description: change you gamemode
    usage: /gamemode [0/1/2/3]
  waterorlavaslime:
    description: asdf
  openmenu:
    description: Open the menu
    usage: /openmenu
  cls:
    description: Clear your chat
    usage: /cls